# Generated by Django 4.0.4 on 2022-05-30 21:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('substancja_czynna', models.CharField(max_length=100)),
                ('cena', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=50)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('pesel', models.IntegerField()),
                ('specjalizacja', models.CharField(choices=[('Internista', 'Internista'), ('Pediatra', 'Pediatra'), ('Ginekolog', 'Ginekolog'), ('Chirurg', 'Chirurg'), ('Ortopeda', 'Ortopeda'), ('Laryngolog', 'Laryngolog'), ('Okulista', 'Okulista'), ('Kardiolog', 'Kardiolog'), ('Urolog', 'Urolog'), ('Psychiatra', 'Psychiatra')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=50)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('pesel', models.IntegerField()),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
                ('data_urodzenia', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('zalecenie', models.TextField()),
                ('lek', models.ManyToManyField(to='przychodnia_app.lek')),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przychodnia_app.lekarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przychodnia_app.pacjent')),
            ],
        ),
    ]
