# Generated by Django 4.0.4 on 2022-05-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lekarz',
            name='pesel',
        ),
        migrations.RemoveField(
            model_name='recepta',
            name='ilosc',
        ),
    ]
