# Generated by Django 4.0.4 on 2022-06-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_app', '0002_remove_lekarz_pesel_remove_recepta_ilosc'),
    ]

    operations = [
        migrations.CreateModel(
            name='IloscLeku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przychodnia_app.lek')),
                ('recepta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przychodnia_app.recepta')),
            ],
        ),
    ]
