# Generated by Django 4.0.4 on 2022-06-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_app', '0003_iloscleku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepta',
            name='lek',
        ),
        migrations.RemoveField(
            model_name='recepta',
            name='zalecenie',
        ),
    ]
