# Generated by Django 4.0.4 on 2022-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_app', '0004_remove_recepta_lek_remove_recepta_zalecenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='iloscleku',
            name='dawkowanie',
            field=models.CharField(default='2x1', max_length=10),
            preserve_default=False,
        ),
    ]
